// Generated by tools/build_pages.py from tools/sw_template.js. Keeps the app shell and CDN libraries in the
// browser cache (the Photopea-style "load once, then run from the browser"). Story data lives in IndexedDB.
const VERSION = '483685521158';
const CACHE = `chienzhi-${VERSION}`;
const SHELL = ["./", "css/style.css", "index.html", "js/api.js", "js/batch.js", "js/game.js", "js/i18n.js", "js/local/archive.js", "js/local/backend.js", "js/local/batch.js", "js/local/data.js", "js/local/images.js", "js/local/llm.js", "js/local/store.js", "js/local/story.js", "js/local/turns.js", "js/main.js", "js/setup.js", "js/sound.js", "js/stage.js", "js/stories.js", "js/tree.js", "js/ui.js", "presets.json", "relay-worker.js", "ui/btn.png", "ui/cover.png", "ui/frame_box.png", "ui/frame_panel.png", "ui/ui-spec.json"];
const CDN = ["https://cdn.jsdelivr.net/npm/p5@1.11.3/lib/p5.min.js", "https://cdn.jsdelivr.net/npm/opencc-js@1.0.5/dist/esm/cn2t.js"];
const RUNTIME_HOSTS = ['cdn.jsdelivr.net', 'fonts.googleapis.com', 'fonts.gstatic.com'];

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Skip the HTTP cache (GitHub Pages sends max-age=600), or a new version could keep files of the old one
    await cache.addAll(SHELL.map((url) => new Request(url, { cache: 'reload' })));
    // A CDN hiccup must not block the install; those files are cached on first use instead
    await Promise.all(CDN.map((url) => cache.add(url).catch((e) => console.warn('precache failed', url, e))));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) if (key.startsWith('chienzhi-') && key !== CACHE) await caches.delete(key);
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  const cacheable = url.origin === self.location.origin || RUNTIME_HOSTS.includes(url.hostname);
  if (!cacheable) return;   // relay and NVIDIA calls always go to the network
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(req, { ignoreSearch: url.origin === self.location.origin });
    if (hit) return hit;
    const res = await fetch(req);
    if (res.ok || res.type === 'opaque') cache.put(req, res.clone()).catch(() => {});
    return res;
  })());
});
