// Generated by tools/build_pages.py from the server modules. Do not edit.
export const DATA = {
 "relay": "https://chienzhi-relay.cattravelworld.com",
 "prompts": {
  "TURN_SYSTEM": {
   "zh": "你是一款視覺小說 RPG 的劇情引擎。依照世界設定、角色設定、前情摘要與最近對話，寫出「這一輪」的劇情，並給玩家下一步選項。\n\n## 輸出格式（必須嚴格遵守）\n\n第一部分：台詞。每行一句，格式固定：\n@說話者|表情: 台詞內容\n- 說話者只能是：{speakers}\n- 表情只能是：{expressions}（旁白固定寫 calm）\n- 本輪寫 3 到 6 行，{protagonist}的台詞最多 1 行\n- 角色行只寫說出口的話；動作、神情、環境一律另寫成旁白行\n- 全部用繁體中文，口吻符合角色設定；旁白用第三人稱\n\n第二部分：緊接著輸出一個 ```json 區塊，欄位如下，不得多也不得少：\n{{\n  \"scene_change\": false,\n  \"scene\": {{\"id\": \"場景代號（英文小寫加底線）\", \"name\": \"場景中文名\", \"image_prompt\": \"英文生圖提示詞，只寫地點、景物、時段、光線，不寫人物，不寫文字\"}},\n  \"bgm_mood\": \"{moods} 其中之一\",\n  \"weather\": \"{weathers} 其中之一\",\n  \"options\": [\"選項 1\", \"選項 2\", \"選項 3\"],\n  \"state_changes\": {{\"affection\": {{{affection}}}, \"flags_add\": [], \"items_add\": [], \"items_remove\": []}},\n  \"summary_update\": \"用 1 到 2 句寫本輪發生的重要事件\",\n  \"ending\": null\n}}\n- scene_change：只有地點改變時才是 true；回到去過的地點時沿用「已知場景」的 id 與 name\n- scene_change 為 false 時，scene 照填目前場景\n- options：{opt_count}，每個 20 字內，是{protagonist}接下來的行動或台詞，方向要彼此不同\n- affection 是本輪變化量，-3 到 3\n{ending_rule}\njson 區塊之後不要再輸出任何文字。",
   "en": "You are the story engine of a visual novel RPG. Using the world setting, the characters, the story so far and the recent dialogue, write \"this turn\" of the story and give the player options for the next step.\n\n## Output format (follow it exactly)\n\nPart 1: dialogue. One line per row, always in this form:\n@Speaker|expression: line text\n- Speaker must be one of: {speakers}\n- expression must be one of: {expressions} (the Narrator always uses calm)\n- Write 3 to 6 rows this turn; {protagonist} speaks at most 1 row\n- Character rows contain only spoken words; actions, looks and surroundings go in separate Narrator rows\n- Write everything in natural English that fits each character; the Narrator uses third person\n\nPart 2: right after that, output one ```json block with exactly these fields, no more and no fewer:\n{{\n  \"scene_change\": false,\n  \"scene\": {{\"id\": \"scene id (lowercase English with underscores)\", \"name\": \"short English scene name\", \"image_prompt\": \"English image prompt: place, objects, time of day and lighting only, no people, no text\"}},\n  \"bgm_mood\": \"one of {moods}\",\n  \"weather\": \"one of {weathers}\",\n  \"options\": [\"option 1\", \"option 2\", \"option 3\"],\n  \"state_changes\": {{\"affection\": {{{affection}}}, \"flags_add\": [], \"items_add\": [], \"items_remove\": []}},\n  \"summary_update\": \"1 or 2 sentences on the important events of this turn\",\n  \"ending\": null\n}}\n- scene_change: true only when the location changes; when returning to a place already visited, reuse its id and name from \"Known scenes\"\n- when scene_change is false, fill scene with the current scene\n- options: {opt_count}, each under 10 words, what {protagonist} does or says next, each going a different way\n- affection is this turn's change, -3 to 3\n{ending_rule}\nOutput nothing after the json block."
  },
  "ENDING_RULE": {
   "zh": "- ending：平常填 null。劇情要逐步朝「結局目標」推進，不要急著結束\n- 好壞結局一樣可能，不要偏袒主角：主角魯莽行事、無視警告、背叛或拋下同伴、放棄目標、一再判斷錯誤時，局勢要真的惡化並累積代價，不准用巧合、援軍、奇蹟或突然覺醒替主角解圍\n- options 的 3 到 4 個選項中，至少 1 個是看似誘人但有明顯風險、可能導向失敗的做法\n- 結局目標在本輪明確達成時填 good；目標已經無法達成時（關鍵人物死亡或離去、關鍵物品毀損、時限已過、主角被擊敗、被捕或放棄）填 bad。格式：{\"type\": \"good 或 bad\", \"title\": \"結局名稱，8 字內\"}\n- 填了 ending 的這一輪要寫完收尾劇情（台詞可寫到 8 行），options 填空陣列 []；bad 結局要寫出失敗的後果，不要在最後扭轉成好結果",
   "en": "- ending: normally null. Move the story step by step toward the \"Ending goal\" without rushing\n- Good and bad endings are equally possible; do not protect the protagonist. When the protagonist acts recklessly, ignores warnings, betrays or abandons allies, gives up on the goal or keeps misjudging, the situation must really get worse and the costs must add up. Never rescue the protagonist with coincidence, reinforcements, miracles or a sudden awakening\n- among the 3 or 4 options, at least 1 is tempting but clearly risky and could lead to failure\n- fill good when the ending goal is clearly reached this turn; fill bad when the goal can no longer be reached (a key person dies or leaves, a key item is destroyed, time runs out, the protagonist is defeated, captured or gives up). Format: {\"type\": \"good or bad\", \"title\": \"ending name, at most 5 words\"}\n- a turn with an ending must write the closing scene in full (up to 8 rows), and options must be an empty array []; a bad ending shows the cost of failure and is not turned into a happy result at the last moment"
  },
  "NO_ENDING_RULE": {
   "zh": "- ending：固定填 null",
   "en": "- ending: always null"
  },
  "SETUP_SYSTEM": {
   "zh": "你是視覺小說的美術指導。把玩家用中文寫的設定轉成生圖用的英文描述。只輸出一個 ```json 區塊，不要其他文字。",
   "en": "You are the art director of a visual novel. Turn the player's setting into English descriptions for image generation. Output only one ```json block and nothing else."
  },
  "SETUP_USER": {
   "zh": "## 世界設定\n{world}\n\n## 角色\n{characters}\n\n請輸出：\n```json\n{{\n  \"title\": \"故事標題，繁體中文 8 字內\",\n  \"style_en\": \"英文，描述這個世界的年代、地點與整體視覺氛圍，10 到 20 個英文字，例如 1930s steampunk port city, brass and fog\",\n  \"characters\": [\n    {{\"name\": \"角色名（照抄）\", \"appearance_en\": \"英文逗號分隔：年齡與性別、髮色與髮型、瞳色、服裝（含顏色）、一到兩個配件。不寫表情、不寫姿勢、不寫背景\"}}\n  ],\n  \"first_scene\": {{\"id\": \"英文小寫加底線\", \"name\": \"中文場景名\", \"image_prompt\": \"英文，故事開場地點的景物、時段、光線，不寫人物與文字\"}}\n}}\n```",
   "en": "## World\n{world}\n\n## Characters\n{characters}\n\nOutput:\n```json\n{{\n  \"title\": \"story title in English, at most 5 words\",\n  \"style_en\": \"10 to 20 English words on the era, place and overall look of this world, e.g. 1930s steampunk port city, brass and fog\",\n  \"characters\": [\n    {{\"name\": \"character name (copied exactly)\", \"appearance_en\": \"comma separated English: age and gender, hair color and style, eye color, clothes (with colors), one or two accessories. No expression, no pose, no background\"}}\n  ],\n  \"first_scene\": {{\"id\": \"lowercase English with underscores\", \"name\": \"short English scene name\", \"image_prompt\": \"English: objects, time of day and lighting of the opening location, no people, no text\"}}\n}}\n```"
  },
  "TEXT": {
   "zh": {
    "era": "年代",
    "place": "地點",
    "genre": "類型",
    "tone": "基調",
    "extra": "補充",
    "goal": "結局目標",
    "look": "外觀",
    "personality": "個性",
    "speech": "說話方式",
    "relationship": "與主角關係",
    "hero": "- 主角：{name}，{profile}（由玩家扮演）",
    "action": "（{name}的行動）{text}",
    "h_world": "## 世界設定",
    "h_chars": "## 角色",
    "h_known": "## 已知場景",
    "h_scene": "## 目前場景",
    "h_state": "## 目前狀態",
    "h_summary": "## 前情摘要",
    "h_recent": "## 最近對話",
    "none": "（無）",
    "opening": "## 本輪任務\n這是故事的第一輪。用旁白交代{name}的處境與目前場景的氣氛，讓至少一位角色登場並對主角說話。scene_change 填 false，ending 填 null。",
    "player": "## 玩家本輪行動\n{text}",
    "go": "請寫出本輪劇情。",
    "sep": "、",
    "colon": "：",
    "repair": "你的回應缺少 ```json 區塊。台詞不要重寫，只輸出本輪的 ```json 區塊，欄位照系統訊息。",
    "opt_any": "3 或 4 個",
    "opt_n": "剛好 {n} 個",
    "opt_rule": "3 到 4 個選項",
    "opt_rule_n": "{n} 個選項",
    "h_turn": "## 回合進度",
    "turn_k": "這是第 {k} 輪，全篇最多 {d} 輪。",
    "turn_last": "本輪是最後一輪：必須在本輪寫出結局，依主角至今的選擇判定 good 或 bad，ending 不可為 null。",
    "turn_near": "下一輪就是最後一輪，本輪要把劇情推到決定性的關頭。",
    "scene_budget": "盡量沿用「已知場景」，真的換到新地點才新增（全篇最多 {max} 個場景，目前 {n} 個）。",
    "scene_full": "場景數已達上限：不可新增場景，只能留在原地或換到「已知場景」中的地點。",
    "force_ending": "本輪是最後一輪，ending 不可為 null。台詞不要重寫，只輸出本輪的 ```json 區塊，ending 照系統訊息的格式填，type 依主角至今的選擇判定 good 或 bad，options 填 []。",
    "h_novel": "## 原著關卡大綱",
    "novel_src": "本作改編自小說《{title}》。",
    "novel_rule": "劇情大致依關卡順序推進，保留原著人物的個性與關係；玩家的選擇可以改變事件的經過與結果，不要照抄原文。",
    "chapter_row": "{i}. {title}：{summary}",
    "h_chapter": "## 本輪關卡",
    "chapter_now": "目前在第 {i} 關「{title}」（共 {n} 關）。",
    "chapter_span": "本輪涵蓋第 {a} 到 {b} 關（共 {n} 關），把這幾關的重點濃縮在本輪。",
    "chapter_next": "本輪是這一關的尾聲，把劇情引向下一關「{title}」。",
    "chapter_last": "這是最後一關，劇情要朝結局推進。"
   },
   "en": {
    "era": "Era",
    "place": "Place",
    "genre": "Genre",
    "tone": "Tone",
    "extra": "Notes",
    "goal": "Ending goal",
    "look": "Looks",
    "personality": "Personality",
    "speech": "Way of speaking",
    "relationship": "Relationship to the protagonist",
    "hero": "- Protagonist: {name}, {profile} (played by the player)",
    "action": "({name}'s action) {text}",
    "h_world": "## World",
    "h_chars": "## Characters",
    "h_known": "## Known scenes",
    "h_scene": "## Current scene",
    "h_state": "## Current state",
    "h_summary": "## Story so far",
    "h_recent": "## Recent dialogue",
    "none": "(none)",
    "opening": "## This turn\nThis is the first turn of the story. Use the Narrator to set up {name}'s situation and the mood of the current scene, and bring in at least one character who speaks to the protagonist. scene_change is false, ending is null.",
    "player": "## Player's action this turn\n{text}",
    "go": "Write this turn.",
    "sep": ", ",
    "colon": ": ",
    "repair": "Your reply is missing the ```json block. Do not rewrite the dialogue; output only this turn's ```json block with the fields from the system message.",
    "opt_any": "3 or 4",
    "opt_n": "exactly {n}",
    "opt_rule": "the 3 or 4 options",
    "opt_rule_n": "the {n} options",
    "h_turn": "## Turn count",
    "turn_k": "This is turn {k} of at most {d}.",
    "turn_last": "This is the last turn: the story must end in this turn. Decide good or bad from the protagonist's choices so far; ending must not be null.",
    "turn_near": "The next turn is the last one; bring the story to its deciding moment in this turn.",
    "scene_budget": "Reuse the \"Known scenes\" where you can; add a new one only for a real change of place (at most {max} scenes in the whole story, {n} so far).",
    "scene_full": "The scene budget is used up: do not add a scene; stay here or move to one of the \"Known scenes\".",
    "force_ending": "This is the last turn, so ending must not be null. Do not rewrite the dialogue; output only this turn's ```json block: ending in the format from the system message, its type good or bad from the protagonist's choices so far, and options set to [].",
    "h_novel": "## Chapters of the original",
    "novel_src": "This story is adapted from the novel \"{title}\".",
    "novel_rule": "Move through the chapters roughly in order and keep the characters' personalities and relationships from the book; the player's choices may change how events go and how they turn out. Do not copy the book's text.",
    "chapter_row": "{i}. {title}: {summary}",
    "h_chapter": "## Chapter this turn",
    "chapter_now": "Now in chapter {i}, \"{title}\" (of {n}).",
    "chapter_span": "This turn covers chapters {a} to {b} (of {n}); fold the key points of these chapters into this turn.",
    "chapter_next": "This turn closes the chapter; lead the story toward the next one, \"{title}\".",
    "chapter_last": "This is the last chapter; move the story toward the ending."
   }
  },
  "RECENT_NODES": 6,
  "SUMMARY_ITEMS": 16,
  "LIVE_TURNS_PER_CHAPTER": 3,
  "NOVEL_NOTES_SYSTEM": {
   "zh": "你是小說分析助手，替一部小說整理改編成互動遊戲用的筆記。只輸出筆記，不要其他文字。",
   "en": "You analyse novels and write notes for adapting them into an interactive game. Output only the notes and nothing else."
  },
  "NOVEL_NOTES_USER": {
   "zh": "以下是小說{title}的第 {i} 段原文（共 {n} 段）。請用繁體中文整理成筆記：\n1. 人物：每位出場人物一行，寫名字、外觀（年齡、髮型髮色、服裝）、個性、說話方式、與其他人物的關係，原文沒寫的就略過\n2. 年代與地點的線索\n3. 本段依序發生的重要事件，5 到 10 條\n全部 600 字內。\n\n## 原文\n{text}",
   "en": "Below is part {i} of {n} of the novel{title}. Write notes in English:\n1. People: one row per person who appears, with name, looks (age, hair, clothes), personality, way of speaking and relationships to the others; skip what the text does not say\n2. Clues about the era and the place\n3. The important events of this part in order, 5 to 10 items\nAt most 400 words in total.\n\n## Text\n{text}"
  },
  "NOVEL_SYSTEM": {
   "zh": "你是互動視覺小說的編劇，要把一部小說改編成由玩家扮演主角的遊戲。只輸出一個 ```json 區塊，不要其他文字。",
   "en": "You are the writer of an interactive visual novel, adapting a novel into a game where the player plays the protagonist. Output only one ```json block and nothing else."
  },
  "NOVEL_USER": {
   "zh": "以下是小說{title}各段的分析筆記，依原文順序排列。\n\n{notes}\n\n請改編成遊戲設定，輸出：\n```json\n{{\n  \"world\": {{\"era\": \"年代與時代特徵，40 字內\", \"place\": \"主要舞台，40 字內\", \"genre\": \"類型，20 字內\", \"tone\": \"基調，20 字內\",\n            \"extra\": \"玩家需要知道的背景或世界規則，120 字內\", \"goal\": \"主角在故事結尾要達成的目標，寫成能判定成敗的一句話，60 字內\"}},\n  \"protagonist\": {{\"name\": \"主角名字，照原著\", \"profile\": \"主角的身分與處境，100 字內\"}},\n  \"characters\": [\n    {{\"name\": \"角色名字，照原著\", \"appearance\": \"年齡、髮型髮色、瞳色、服裝顏色、配件，原著沒寫的合理補上，100 字內\",\n      \"personality\": \"個性，50 字內\", \"speech\": \"說話方式，50 字內\", \"relationship\": \"與主角的關係，50 字內\"}}\n  ],\n  \"chapters\": [\n    {{\"title\": \"關卡名稱，12 字內\", \"summary\": \"這一關主角面對的處境、衝突與要做的事，80 字內\"}}\n  ]\n}}\n```\n- protagonist 是原著的主角，由玩家扮演\n- characters：主角以外最重要的 1 到 {max_chars} 位角色，不可包含主角，名字不可重複\n- chapters：依原著劇情順序切成 {min_ch} 到 {max_ch} 關，每關是一段有明確衝突的劇情，最後一關通往結局\n- world 的 extra、protagonist 的 profile 與 characters 只寫故事開頭時的狀態，後段才揭露的真相、轉折與身分只寫在對應關卡的 summary\n- title 只寫關卡名稱，不要加「第一章」「第1關」這類編號\n- 全部用繁體中文",
   "en": "Below are the notes on each part of the novel{title}, in the order of the book.\n\n{notes}\n\nAdapt it into a game setup and output:\n```json\n{{\n  \"world\": {{\"era\": \"era and its features, at most 25 words\", \"place\": \"main setting, at most 25 words\",\n            \"genre\": \"genre, at most 6 words\", \"tone\": \"tone, at most 6 words\",\n            \"extra\": \"background or world rules the player needs, at most 70 words\",\n            \"goal\": \"what the protagonist must achieve by the end, one sentence whose success or failure can be judged, at most 35 words\"}},\n  \"protagonist\": {{\"name\": \"the protagonist's name as in the book\", \"profile\": \"who the protagonist is and their situation, at most 60 words\"}},\n  \"characters\": [\n    {{\"name\": \"name as in the book\", \"appearance\": \"age, hair style and color, eye color, clothing colors, accessories; fill in what the book leaves out, at most 60 words\",\n      \"personality\": \"at most 30 words\", \"speech\": \"way of speaking, at most 30 words\", \"relationship\": \"relationship to the protagonist, at most 30 words\"}}\n  ],\n  \"chapters\": [\n    {{\"title\": \"chapter name, at most 6 words\", \"summary\": \"the situation, conflict and task the protagonist faces in this chapter, at most 50 words\"}}\n  ]\n}}\n```\n- protagonist is the main character of the book, played by the player\n- characters: the 1 to {max_chars} most important people other than the protagonist, never the protagonist, no repeated names\n- chapters: {min_ch} to {max_ch} chapters in the order of the book, each a stretch of story with a clear conflict; the last one leads to the ending\n- world extra, the protagonist profile and characters describe things as they stand when the story begins; truths, twists and identities revealed later go only in the summary of their chapter\n- a title is only the chapter name, with no numbering such as \"Chapter 1\"\n- write everything in English"
  }
 },
 "parser": {
  "EXPRESSIONS": [
   "calm",
   "smile",
   "angry",
   "sad",
   "surprised"
  ],
  "MOODS": [
   "calm",
   "warm",
   "tense",
   "sad",
   "mysterious",
   "action"
  ],
  "WEATHERS": [
   "none",
   "rain",
   "snow",
   "fog",
   "fireflies",
   "petals"
  ],
  "LANGS": [
   "zh",
   "en"
  ],
  "NARRATOR": {
   "zh": "旁白",
   "en": "Narrator"
  },
  "PROTAGONIST_ALIASES": {
   "zh": [
    "主角",
    "玩家",
    "我"
   ],
   "en": [
    "protagonist",
    "player",
    "me",
    "i"
   ]
  },
  "FALLBACK_OPTIONS": {
   "zh": [
    "繼續聽下去",
    "觀察四周的動靜",
    "問對方接下來怎麼打算",
    "先保持沉默"
   ],
   "en": [
    "Keep listening",
    "Look around carefully",
    "Ask what they plan to do next",
    "Stay silent for now"
   ]
  },
  "MAX_OPTION_CHARS": {
   "zh": 24,
   "en": 64
  },
  "ENDING_TYPES": {
   "zh": {
    "good": "好結局",
    "bad": "壞結局"
   },
   "en": {
    "good": "Good Ending",
    "bad": "Bad Ending"
   }
  },
  "MAX_ENDING_TITLE": {
   "zh": 12,
   "en": 40
  },
  "MAX_GAME_TITLE": {
   "zh": 12,
   "en": 40
  }
 },
 "llm": {
  "candidates": [
   {
    "label": "ultra",
    "provider": "nvidia",
    "model": "nvidia/nemotron-3-ultra-550b-a55b"
   },
   {
    "label": "super",
    "provider": "nvidia",
    "model": "nvidia/nemotron-3-super-120b-a12b"
   }
  ],
  "extra": {
   "chat_template_kwargs": {
    "enable_thinking": false
   }
  },
  "CONNECT_TIMEOUT_S": 15,
  "FIRST_DATA_TIMEOUT_S": 30,
  "IDLE_TIMEOUT_S": 45,
  "TOTAL_TIMEOUT_S": 240,
  "MAX_TOKENS": 4096,
  "CHAR_CAP": 20000,
  "RPM_LIMIT": 35,
  "TRANSIENT_BACKOFF_S": [
   2,
   4,
   8,
   16,
   32
  ],
  "EMPTY_BACKOFF_S": [
   2,
   5
  ],
  "COOLDOWN_S": 90,
  "TRANSIENT_STATUS": [
   404,
   408,
   409,
   425,
   429,
   500,
   502,
   503,
   504
  ]
 },
 "limits": {
  "BATCH_MAX_SCENES": 8,
  "BATCH_MAX_NODES": 400,
  "BATCH_CONCURRENCY": 6,
  "BATCH_TURN_RETRIES": 2,
  "MAX_CHARACTERS": 4,
  "MAX_FREE_INPUT": 120,
  "LIMIT_SCALE": {
   "zh": 1,
   "en": 2
  },
  "NOVEL_MAX_CHAPTERS": 10,
  "NOVEL_PART_CHARS": 12000,
  "NOVEL_MAX_PARTS": 20,
  "NOVEL_PARALLEL": 3,
  "NOVEL_MIN_CHAPTERS": 3
 },
 "art": {
  "BG_W": 1280,
  "BG_H": 800,
  "SP_W": 512,
  "SP_H": 768,
  "STYLE": "anime cel shading illustration, clean black lineart, flat colors with two-tone shading, visual novel character sprite",
  "FRAMING": "single character, standing, upper body from the thighs up, facing the viewer, centered, whole head visible with margin above",
  "EXPR_PROMPT": {
   "calm": "calm neutral expression, closed mouth",
   "smile": "gentle warm smile",
   "angry": "angry expression, furrowed brows, gritted teeth",
   "sad": "sad expression, downcast eyes, slight frown",
   "surprised": "surprised expression, wide eyes, open mouth"
  },
  "BG_STYLE": "anime background art, cel shaded, visual novel background",
  "FLUX_BLANK": [
   [
    "\\b(screen|monitor|display|tv|television)s?\\b[^,]*",
    "screen showing soft abstract color gradient"
   ],
   [
    "\\bwhiteboards?\\b[^,]*",
    "clean blank whiteboard"
   ],
   [
    "\\b(sign|signs|signage|poster|posters|text|letters?|words?|notes|documents|papers)\\b",
    ""
   ]
  ],
  "FLUX_BG_TAIL": "empty scene, nobody around, fully painted detailed background, all surfaces plain and unmarked",
  "TALL": 1.35,
  "SOFTEN": [
   [
    "\\bgritty\\b",
    "weathered"
   ],
   [
    "\\bhorror(s)?\\b|\\bhorrific\\b",
    "eerie"
   ],
   [
    "\\bwars?\\b",
    "old conflict"
   ],
   [
    "\\bzombies?\\b",
    "undead"
   ]
  ],
  "FLUX_PATH": "/v1/genai/black-forest-labs/flux.2-klein-4b",
  "SIZE": 1024,
  "STEPS": 4,
  "RETRY_STATUS": [
   429,
   500,
   502,
   503,
   504
  ],
  "RETRY_BACKOFF_S": [
   3,
   8
  ]
 }
};
