"""Build the GitHub Pages version into dist/pages: the web client running with a browser-side backend.

- copies web/ and marks index.html as local mode (<meta name="cg-local">)
- writes js/local/data.js: prompt text, parser and LLM constants and art prompts taken from the server modules,
  so the browser port uses exactly the same text; only the hosted NVIDIA models are listed, never local endpoints
- copies the demo story (final images only, no .raw intermediates) and writes demo/index.json
- bakes in the built-in relay (RELAY) so players only enter their own NVIDIA key, and copies relay/worker.js
  as relay-worker.js for anyone who wants to run their own relay
- writes sw.js, which keeps the app shell and CDN libraries in the browser cache
- refuses to finish when any secret from .env appears in the output

Run from the project root: python tools/build_pages.py
"""
import hashlib
import json
import pathlib
import re
import shutil
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from server import asset_service, config, nvidia_image, prompts, turn_parser, turn_service  # noqa: E402

OUT = ROOT / "dist" / "pages"
DEMO_GAMES = ["g_20260925_145203"]
SKIP_ASSET = re.compile(r"\.(raw|donor|face|eyes)\.|batch\.json$")
CDN = ["https://cdn.jsdelivr.net/npm/p5@1.11.3/lib/p5.min.js",
       "https://cdn.jsdelivr.net/npm/opencc-js@1.0.5/dist/esm/cn2t.js"]
# Public CORS relay: the Cloudflare Worker in relay/worker.js on the owner's account (holds no key of its own)
RELAY = "https://chienzhi-relay.cattravelworld.com"
# Hosted models only (same ids and order as config.CANDIDATES without the local endpoint)
CANDIDATES = [{"label": "ultra", "provider": "nvidia", "model": "nvidia/nemotron-3-ultra-550b-a55b"},
              {"label": "super", "provider": "nvidia", "model": "nvidia/nemotron-3-super-120b-a12b"}]


def data_module() -> str:
    p, tp, a = prompts, turn_parser, asset_service
    data = {
        "relay": RELAY,
        "prompts": {k: getattr(p, k) for k in ("TURN_SYSTEM", "ENDING_RULE", "NO_ENDING_RULE", "SETUP_SYSTEM",
                                               "SETUP_USER", "TEXT", "RECENT_NODES", "SUMMARY_ITEMS")},
        "parser": {k: getattr(tp, k) for k in ("EXPRESSIONS", "MOODS", "WEATHERS", "LANGS", "NARRATOR",
                                               "PROTAGONIST_ALIASES", "FALLBACK_OPTIONS", "MAX_OPTION_CHARS",
                                               "ENDING_TYPES", "MAX_ENDING_TITLE", "MAX_GAME_TITLE")},
        "llm": {"candidates": CANDIDATES, "extra": config.NO_THINK,
                **{k: getattr(config, k) for k in ("CONNECT_TIMEOUT_S", "FIRST_DATA_TIMEOUT_S", "IDLE_TIMEOUT_S",
                                                   "TOTAL_TIMEOUT_S", "MAX_TOKENS", "CHAR_CAP", "RPM_LIMIT",
                                                   "TRANSIENT_BACKOFF_S", "EMPTY_BACKOFF_S", "COOLDOWN_S")},
                "TRANSIENT_STATUS": sorted(config.TRANSIENT_STATUS)},
        "limits": {**{k: getattr(config, k) for k in ("BATCH_MAX_SCENES", "BATCH_MAX_NODES", "BATCH_CONCURRENCY",
                                                   "BATCH_TURN_RETRIES")},
                   "MAX_CHARACTERS": turn_service.MAX_CHARACTERS,
                   "MAX_FREE_INPUT": turn_service.MAX_FREE_INPUT, "LIMIT_SCALE": turn_service.LIMIT_SCALE},
        "art": {**{k: getattr(a, k) for k in ("BG_W", "BG_H", "SP_W", "SP_H", "STYLE", "FRAMING", "EXPR_PROMPT",
                                              "BG_STYLE", "FLUX_BLANK", "FLUX_BG_TAIL")},
                "TALL": 1.35, "SOFTEN": nvidia_image.SOFTEN, "FLUX_PATH": nvidia_image.URL.split(".com", 1)[1],
                "SIZE": nvidia_image.SIZE, "STEPS": nvidia_image.STEPS,
                "RETRY_STATUS": sorted(nvidia_image.RETRY_STATUS), "RETRY_BACKOFF_S": nvidia_image.RETRY_BACKOFF_S},
    }
    body = json.dumps(data, ensure_ascii=False, indent=1)
    return ("// Generated by tools/build_pages.py from the server modules. Do not edit.\n"
            f"export const DATA = {body};\n")


def copy_demo() -> list[str]:
    files = []
    for gid in DEMO_GAMES:
        src = ROOT / "saves" / "games" / gid
        for f in sorted(src.rglob("*")):
            rel = f.relative_to(src).as_posix()
            if f.is_dir() or SKIP_ASSET.search(rel):
                continue
            dest = OUT / "demo" / gid / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(f, dest)
            files.append(f"{gid}/{rel}")
    return files


def scrub_models(files: list[str]) -> None:
    """Node and game records name the model that wrote them; a local model name is replaced by "local"."""
    local = config.ENV.get("LOCAL_LLM_MODEL")
    if not local:
        return
    for rel in files:
        if rel.endswith(".json"):
            path = OUT / "demo" / rel
            text = path.read_text(encoding="utf-8")
            if local in text:
                path.write_text(text.replace(local, "local"), encoding="utf-8")


def service_worker(version: str) -> str:
    shell = sorted(p.relative_to(OUT).as_posix() for p in OUT.rglob("*")
                   if p.is_file() and not p.relative_to(OUT).as_posix().startswith("demo/"))
    shell = ["./"] + [s for s in shell if s != "sw.js"]
    return (ROOT / "tools" / "sw_template.js").read_text(encoding="utf-8") \
        .replace("__VERSION__", version) \
        .replace("__SHELL__", json.dumps(shell, ensure_ascii=False)) \
        .replace("__CDN__", json.dumps(CDN))


def secret_scan() -> None:
    """Every .env value that could identify a private endpoint or key must be absent from the output."""
    needles = [v for k, v in config.ENV.items() if v and len(v) >= 6 and
               (k.endswith("_API_KEY") or k.startswith("LOCAL_LLM"))]
    for k, v in config.ENV.items():
        if k == "LOCAL_LLM_BASE_URL" and v:
            host = re.sub(r"^https?://", "", v).split("/")[0].split(":")[0]
            needles.append(host)
    for f in OUT.rglob("*"):
        if f.is_file():
            data = f.read_bytes()
            for n in needles:
                if n.encode() in data:
                    raise SystemExit(f"secret found in {f.relative_to(OUT)}; build stopped")


def main() -> None:
    if OUT.exists():
        shutil.rmtree(OUT)
    shutil.copytree(ROOT / "web", OUT)
    index = OUT / "index.html"
    html = index.read_text(encoding="utf-8")
    index.write_text(html.replace('<meta charset="utf-8">',
                                  '<meta charset="utf-8">\n<meta name="cg-local" content="1">', 1), encoding="utf-8")
    (OUT / "js" / "local" / "data.js").write_text(data_module(), encoding="utf-8")
    shutil.copy2(ROOT / "relay" / "worker.js", OUT / "relay-worker.js")
    files = copy_demo()
    scrub_models(files)
    digest = hashlib.sha1()
    for rel in files:
        digest.update(rel.encode())
        digest.update((OUT / "demo" / rel).read_bytes())
    demo_version = digest.hexdigest()[:12]
    (OUT / "demo" / "index.json").write_text(json.dumps({"version": demo_version, "games": DEMO_GAMES,
                                                         "files": files}, indent=1), encoding="utf-8")
    shell_digest = hashlib.sha1()
    for p in sorted(OUT.rglob("*")):
        if p.is_file():
            shell_digest.update(p.relative_to(OUT).as_posix().encode())
            shell_digest.update(p.read_bytes())
    (OUT / "sw.js").write_text(service_worker(shell_digest.hexdigest()[:12]), encoding="utf-8")
    (OUT / ".nojekyll").write_text("", encoding="utf-8")
    secret_scan()
    size = sum(f.stat().st_size for f in OUT.rglob("*") if f.is_file()) / 1e6
    print(f"built {OUT} ({size:.1f} MB, demo {demo_version}, {len(files)} demo files)")


if __name__ == "__main__":
    main()
