"""Ten test stories for tools.e2e_stories: 5 written in Chinese, 5 in English, each with its own world,
cast and ending goal. `pushes` are free inputs that steer toward the goal; `aim` bad pushes toward failure."""

ZH_FINAL = "我決定不再拖延，現在就賭上一切，把這件事做個了斷。"
EN_FINAL = "I stop hesitating and risk everything right now to settle this once and for all."

STORIES = [
    {
        "key": "zh1_ghost_market", "lang": "zh", "aim": "good",
        "world": {"era": "清末光緒年間", "place": "江南山城外，只在月圓夜出現的鬼市", "genre": "志怪懸疑",
                  "tone": "幽微、帶點人情味", "extra": "鬼市用記憶當錢，賣掉的記憶再也回不來",
                  "goal": "在天亮前從鬼市贖回妹妹失去的魂魄"},
        "hero": ("小滿", "山城藥舖的學徒，妹妹昨夜突然失了魂"),
        "chars": [
            {"name": "青蘿", "appearance": "外表 18 歲的狐仙少女，及腰墨綠色長髮，金色豎瞳，頭上一對白色狐耳，淺綠色交領襦裙，腰間繫紅繩鈴鐺",
             "personality": "狡黠愛捉弄人，其實心軟", "speech": "說話拖長尾音，常反問", "relationship": "鬼市的引路人，對主角的藥香很好奇"},
            {"name": "老墨", "appearance": "看不出年紀的瘦高男子，灰白長髮用木簪束起，戴半張黑色面具，深紫色長袍，手持算盤",
             "personality": "精明冷淡，守規矩", "speech": "惜字如金，開口就是價錢", "relationship": "鬼市掌櫃，收著妹妹的魂"},
        ],
        "pushes": ["我去找老墨，問他妹妹的魂要用什麼換。", "我願意用自己最珍貴的一段記憶，換回妹妹的魂。",
                   "趁天還沒亮，我拿著贖回的魂魄跑回藥舖，讓妹妹醒過來。"],
    },
    {
        "key": "zh2_deep_station", "lang": "zh", "aim": "good",
        "world": {"era": "2150 年", "place": "太平洋海底三千公尺的研究站「潮汐七號」", "genre": "科幻驚悚",
                  "tone": "緊張、壓迫", "extra": "主電源被人為切斷，備用氧氣只剩十二小時",
                  "goal": "在氧氣耗盡前揪出破壞者，讓全員搭逃生艙撤離"},
        "hero": ("林遠", "研究站的維修工程師，熟悉每一條管線"),
        "chars": [
            {"name": "顧晴", "appearance": "35 歲女性，黑色俐落短髮，深褐色眼睛，白色與橘色相間的研究站制服，左臂戴著平板護腕",
             "personality": "冷靜果斷，背負壓力", "speech": "命令句多，偶爾流露疲憊", "relationship": "站長，主角的上司"},
            {"name": "汐", "appearance": "外表 14 歲的全息投影少女，淺藍色半透明短髮，青色發光眼睛，白色連帽外套，身體邊緣有淡淡的藍光",
             "personality": "天真好奇，對人類情感很著迷", "speech": "用詞精確，喜歡報數字", "relationship": "研究站的管理 AI，最信任主角"},
        ],
        "pushes": ["我和汐一起調出主電源被切斷那一刻的監視紀錄，找出是誰做的。", "我當面拿證據質問破壞者，要他交出逃生艙的控制碼。",
                   "我修好逃生艙的線路，帶所有人撤離潮汐七號。"],
    },
    {
        "key": "zh3_night_market", "lang": "zh", "aim": "good",
        "world": {"era": "現代", "place": "台南一座有六十年歷史的老夜市", "genre": "美食喜劇",
                  "tone": "熱鬧、搞笑、有溫度", "extra": "連鎖集團想買下整條夜市，揚言用料理大賽決定攤位去留",
                  "goal": "在夜市料理大賽贏過連鎖集團的主廚，保住阿嬤的蚵仔煎攤"},
        "hero": ("阿佑", "剛辭掉工作回老家的上班族，廚藝普通但很會吃"),
        "chars": [
            {"name": "小葵", "appearance": "24 歲女性，栗色丸子頭，大大的黑色眼睛，黃色 T 恤外綁紅色圍裙，手腕套著一串彩色髮圈",
             "personality": "熱血直率，嘴硬心軟", "speech": "講話很快，愛用台語口頭禪", "relationship": "隔壁剉冰攤的青梅竹馬"},
            {"name": "杜蘭", "appearance": "32 歲男性，梳得一絲不苟的金色油頭，冰藍色眼睛，純白雙排扣主廚服，胸前別著金色湯匙徽章",
             "personality": "驕傲自負，但尊重真正的好料理", "speech": "中英夾雜，愛說「完美」", "relationship": "連鎖集團的明星主廚，大賽對手"},
        ],
        "pushes": ["我去請教阿嬤蚵仔煎醬汁的祖傳祕方。", "我和小葵把剉冰攤的古早味糖水加進醬汁，研發新版蚵仔煎。",
                   "決賽開始，我端出新版蚵仔煎，請評審和杜蘭一起試吃。"],
    },
    {
        "key": "zh4_wuxia_pass", "lang": "zh", "aim": "good",
        "world": {"era": "北宋末年", "place": "風雪中的雁門關外，一間孤零零的客棧", "genre": "武俠",
                  "tone": "蒼涼、俠義", "extra": "客棧裡的每個人都在等同一封密信",
                  "goal": "護送密信平安出關，並揭穿潛伏在客棧的內奸"},
        "hero": ("沈白", "年輕的鏢師，第一次獨自押鏢"),
        "chars": [
            {"name": "燕十三娘", "appearance": "27 歲女刀客，黑色高馬尾，丹鳳眼，暗紅色勁裝外披白色毛領斗篷，背著一柄長刀",
             "personality": "爽朗豪氣，恩怨分明", "speech": "說話直來直往，愛喝酒", "relationship": "客棧裡偶遇的江湖人，身分成謎"},
            {"name": "老駱", "appearance": "60 歲男說書人，花白鬍子，瞇瞇眼，褪色的藍布長衫，手拿一把破摺扇",
             "personality": "看似糊塗，其實什麼都知道", "speech": "說話像在說書，愛賣關子", "relationship": "客棧常客，似乎認識主角的師父"},
        ],
        "pushes": ["我暗中觀察誰在半夜打探密信的下落。", "我設下假密信的圈套，引內奸現身。",
                   "揭穿內奸後，我趁風雪稍停，帶著真密信衝出雁門關。"],
    },
    {
        "key": "zh5_metro_winter", "lang": "zh", "aim": "bad",
        "world": {"era": "核冬天後第十年", "place": "廢墟化的台北，地下捷運站裡的倖存者聚落", "genre": "末日生存",
                  "tone": "冷冽、帶一絲希望", "extra": "淨水機壞了，聚落的存水只夠撐七天",
                  "goal": "找到淨水機的零件並平安帶回，讓聚落撐過這個冬天"},
        "hero": ("阿岳", "聚落裡最年輕的探勘隊員，衝動但勇敢"),
        "chars": [
            {"name": "陳姐", "appearance": "45 歲女性，灰黑色短髮，眼角有細紋，深褐色眼睛，軍綠色舊外套上縫滿補丁，腰間掛著手電筒",
             "personality": "堅毅務實，照顧每個人", "speech": "語氣平穩，說一不二", "relationship": "聚落首領，把主角當孩子看"},
            {"name": "小灰", "appearance": "13 歲少年，亂翹的灰色短髮，機靈的黑色眼睛，過大的灰色連帽衣，臉上戴著破舊防毒面具",
             "personality": "膽小但反應快", "speech": "講話結結巴巴，緊張時更嚴重", "relationship": "拾荒少年，跟著主角出任務"},
        ],
        "pushes": ["我不聽陳姐勸阻，決定獨自穿過輻射最強的中正紀念堂廢墟去找零件。",
                   "我把防毒面具的濾芯讓給小灰，自己冒著輻射繼續往深處走。",
                   "暴風雪來了，我還是硬闖崩塌的隧道想搶先拿到零件。"],
    },
    {
        "key": "en1_blackmoor", "lang": "en", "aim": "good",
        "world": {"era": "1888, late Victorian England", "place": "Blackmoor Manor on the windswept Yorkshire moors",
                  "genre": "gothic mystery", "tone": "eerie and melancholic",
                  "extra": "Every night a child's music box plays in a room that was bricked up forty years ago",
                  "goal": "Lay the manor's ghost to rest before the last candle of the vigil burns out"},
        "hero": ("Eliza Grey", "a young spirit medium invited to the manor, sharp-eyed and sceptical of her own gift"),
        "chars": [
            {"name": "Edmund", "appearance": "40-year-old man, neatly combed dark brown hair with grey at the temples, pale grey eyes, black Victorian frock coat, white cravat, silver signet ring",
             "personality": "proud and guarded, haunted by guilt", "speech": "formal and clipped, avoids the past",
             "relationship": "Lord of Blackmoor Manor who hired you"},
            {"name": "Clara", "appearance": "ghost of a 10-year-old girl, long pale blonde hair with a blue ribbon, pale blue eyes, old-fashioned white lace dress, faintly translucent",
             "personality": "lonely and playful, afraid of the dark cellar", "speech": "speaks in riddles and nursery rhymes",
             "relationship": "the manor's ghost, curious about you"},
        ],
        "pushes": ["I ask Clara what happened in the bricked-up room forty years ago.",
                   "I confront Edmund with what Clara told me and ask him to open the bricked-up room.",
                   "We open the room together, and I return Clara's music box to her so she can finally rest."],
    },
    {
        "key": "en2_dustreach", "lang": "en", "aim": "good",
        "world": {"era": "the 2300s, frontier space colonies", "place": "Dustreach, a lawless mining moon with one dusty main street",
                  "genre": "space western", "tone": "gritty and witty",
                  "extra": "The railway syndicate has bought every water well on the moon except one",
                  "goal": "Stop the railway syndicate from seizing the colony's last water well"},
        "hero": ("Jack Rook", "a drifter with a fast hand and a slow temper, just off the supply shuttle"),
        "chars": [
            {"name": "Maya", "appearance": "30-year-old woman, sun-bleached auburn braid, green eyes, freckles, brown leather duster over a white shirt, silver star badge",
             "personality": "stubborn, fair, tired of losing", "speech": "dry, short sentences, calls you 'stranger'",
             "relationship": "the colony's sheriff, short on deputies"},
            {"name": "Brass", "appearance": "android bartender shaped like a tall man, polished copper plating, round glowing amber eyes, black vest and bow tie over the metal body",
             "personality": "polite, secretly sentimental", "speech": "overly formal, quotes old westerns",
             "relationship": "runs the saloon, hears every rumor"},
        ],
        "pushes": ["I ask Brass which syndicate men have been asking about the last well.",
                   "Maya and I catch the syndicate foreman forging the well's deed and take the papers as proof.",
                   "At high noon I face the syndicate boss in the street with Maya beside me and show the whole town the forged deed."],
    },
    {
        "key": "en3_honeyvale", "lang": "en", "aim": "good",
        "world": {"era": "a timeless storybook age", "place": "Honeyvale, a village where baked goods carry small spells",
                  "genre": "cozy fantasy", "tone": "warm and whimsical",
                  "extra": "The whole village fell into an enchanted sleep after the moon festival",
                  "goal": "Bake the Moon Loaf before the next moonrise to wake the sleeping village"},
        "hero": ("Pip", "an apprentice baker, the only villager still awake"),
        "chars": [
            {"name": "Granny Wren", "appearance": "elderly woman, silver hair in a tidy bun, twinkling brown eyes, round spectacles, flour-dusted blue apron over a lavender dress",
             "personality": "kind, mischievous, forgetful", "speech": "calls everyone 'dumpling', gives advice in recipes",
             "relationship": "your baking teacher, half asleep and drifting in dreams"},
            {"name": "Rowan", "appearance": "19-year-old young man, messy chestnut hair, hazel eyes, forest-green courier cloak, brass-buckled satchel",
             "personality": "brave, a little clumsy", "speech": "cheerful and fast, loves bad puns",
             "relationship": "the royal courier who arrived after the spell fell"},
        ],
        "pushes": ["I ask Granny Wren in her dream for the Moon Loaf recipe.",
                   "Rowan and I gather the last ingredient, moonflower honey, from the hill above the village.",
                   "I bake the Moon Loaf just as the moon rises and share it with the whole village."],
    },
    {
        "key": "en4_neo_kowloon", "lang": "en", "aim": "bad",
        "world": {"era": "2079", "place": "Neo-Kowloon, a rain-soaked vertical megacity of neon and noodle stalls",
                  "genre": "cyberpunk heist", "tone": "tense and stylish",
                  "extra": "The Kagero corporation stole a memory chip holding a whole district's savings",
                  "goal": "Steal the memory chip back from the Kagero tower before midnight"},
        "hero": ("Vex", "a burned-out netrunner with one last favor to repay"),
        "chars": [
            {"name": "Rin", "appearance": "26-year-old woman, asymmetric neon-pink bob, dark eyes with glowing cyan implants, black cropped racing jacket, fingerless gloves",
             "personality": "reckless, loyal, hates corporations", "speech": "slangy and teasing",
             "relationship": "your getaway driver and oldest friend"},
            {"name": "Hollow", "appearance": "50-year-old man, slicked-back white hair, mirrored sunglasses, charcoal three-piece suit, chrome prosthetic right hand",
             "personality": "smooth, calculating, untrustworthy", "speech": "soft-spoken, every sentence a deal",
             "relationship": "corporate fixer who offers you inside help"},
        ],
        "pushes": ["I ignore Rin's warning and accept Hollow's offer of a tower access key without checking it.",
                   "I go in alone and jack straight into the Kagero core, skipping the ice-breaker Rin prepared.",
                   "The alarms are screaming but I stay plugged in to grab the chip myself instead of retreating."],
    },
    {
        "key": "en5_isla_serpiente", "lang": "en", "aim": "good",
        "world": {"era": "1715, the golden age of sail", "place": "Isla Serpiente, a jungle island in the Caribbean",
                  "genre": "swashbuckling adventure", "tone": "bold and humorous",
                  "extra": "A ghost fleet rises from the sea every hundred years to reclaim the island's cursed gold",
                  "goal": "Find the cursed treasure and lift the curse before the ghost fleet arrives at dawn"},
        "hero": ("Kit", "a cabin girl who just inherited a leaky ship and a treasure map"),
        "chars": [
            {"name": "Red Vane", "appearance": "45-year-old pirate captain, wild red beard and hair under a black tricorn hat, one gold earring, crimson coat with brass buttons",
             "personality": "boastful, greedy, secretly brave", "speech": "loud and theatrical, full of sea slang",
             "relationship": "a rival captain who wants the same treasure"},
            {"name": "Solenne", "appearance": "22-year-old woman, long wavy black hair, deep brown eyes, white shirt with rolled sleeves, navy sash, brass spyglass",
             "personality": "clever, calm, loves the stars", "speech": "precise, speaks in compass bearings",
             "relationship": "your navigator and only crew member"},
        ],
        "pushes": ["Solenne and I follow the map's star bearings to the temple in the heart of the jungle.",
                   "I propose a truce to Red Vane: we split the treasure only if we lift the curse together.",
                   "At dawn I throw the cursed gold back into the sea to lift the curse as the ghost fleet appears."],
    },
    {
        # Business English practice: not one of the ten, run it by key; keeps its progress in save slot 2
        "key": "en6_workplace_english", "lang": "en", "aim": "good", "save_slot": 1,
        "world": {"era": "Present day", "place": "The Singapore office of a global software company",
                  "genre": "workplace drama for business English practice", "tone": "realistic, supportive, a little tense",
                  "extra": "The protagonist is practising business English. Characters speak clear professional English, "
                           "and Priya politely suggests a more professional phrasing when the protagonist sounds too casual",
                  "goal": "Get the client to approve the project proposal at Friday's meeting"},
        "hero": ("Alex Chen", "a junior project coordinator from Taipei in their first month at the Singapore office"),
        "chars": [
            {"name": "Priya Nair", "appearance": "38-year-old woman, shoulder-length straight black hair, warm brown eyes, navy blazer over a cream blouse, silver lanyard badge",
             "personality": "demanding but fair, a patient mentor", "speech": "concise business English, often rephrases your sentences more professionally",
             "relationship": "your team manager"},
            {"name": "Daniel Hartley", "appearance": "50-year-old man, short grey hair, rimless glasses, charcoal suit, light blue shirt with no tie, smartwatch",
             "personality": "sceptical, detail-oriented, values honesty", "speech": "formal British English, asks sharp follow-up questions",
             "relationship": "procurement director at the client company"},
        ],
        "pushes": ["Could we schedule a quick meeting this afternoon to align on the project timeline?",
                   "I'd like to clarify the budget assumptions before we present them to Daniel.",
                   "Thank you for raising that concern. Let me walk you through how we will reduce the delivery risk."],
        "final": "To sum up, our proposal meets your timeline and budget. May I ask whether you are ready to approve it today?",
    },
]
