// Generated by tools/build_pages.py from tools/sw_template.js. Keeps the app shell and CDN libraries in the
// browser cache (the Photopea-style "load once, then run from the browser"). Story data lives in IndexedDB.
const VERSION = '__VERSION__';
const CACHE = `chienzhi-${VERSION}`;
const SHELL = __SHELL__;
const CDN = __CDN__;
const RUNTIME_HOSTS = ['cdn.jsdelivr.net', 'fonts.googleapis.com', 'fonts.gstatic.com'];

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    await cache.addAll(SHELL);
    // A CDN hiccup must not block the install; those files are cached on first use instead
    await Promise.all(CDN.map((url) => cache.add(url).catch((e) => console.warn('precache failed', url, e))));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) if (key.startsWith('chienzhi-') && key !== CACHE) await caches.delete(key);
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  const cacheable = url.origin === self.location.origin || RUNTIME_HOSTS.includes(url.hostname);
  if (!cacheable) return;   // relay and NVIDIA calls always go to the network
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(req, { ignoreSearch: url.origin === self.location.origin });
    if (hit) return hit;
    const res = await fetch(req);
    if (res.ok || res.type === 'opaque') cache.put(req, res.clone()).catch(() => {});
    return res;
  })());
});
